version: '2'
services:
  weblate:
    image: weblate/weblate
    links:
      - database
      - cache
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
    environment:
      - WEBLATE_ENABLE_HTTPS=1
  database:
    image: postgres:9.6-alpine
    env_file:
      - ./environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  cache:
    image: redis:4-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - weblate
    restart: always
    environment:
      STAGE: production
      PROXY_READ_TIMEOUT: 3600
volumes:
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
