weblate:
  build: weblate
  links:
    - database
    - cache
  ports:
    - "8000:8000"
  volumes:
    - /app/data
    - ./weblate:/app/etc:ro
  env_file:
    - ./weblate/environment
database:
  image: postgres:9.4
  env_file:
    - ./weblate/environment
cache:
    image: memcached:1.4
