# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Docker Hub Description
on:
  push:
    branches:
    - main
    paths:
    - README.md
    - .github/workflows/readme-sync.yml
jobs:
  sync-readme:
    runs-on: ubuntu-24.04
    if: ${{ github.repository == 'WeblateOrg/docker'}}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae # v4.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: weblate/weblate
        short-description: ${{ github.event.repository.description }}
permissions:
  contents: read
