# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Docker Hub Description
on:
  push:
    branches:
    - main
    paths:
    - README.md
    - .github/workflows/readme-sync.yml
jobs:
  sync-readme:
    runs-on: ubuntu-24.04
    if: ${{ github.repository == 'WeblateOrg/docker'}}
    steps:
    - name: Checkout
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        persist-credentials: false
    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: weblate/weblate
        short-description: ${{ github.event.repository.description }}
permissions:
  contents: read
